apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  # para publicar pra fora
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: wordpress
  externalIPs:
    - 192.168.0.38
