apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 192.168.0.38