apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # para publicar pra fora
  type: LoadBalancer
  ports:
    # ao omitir targetPort, é usado o valor port memo
    - port: 80
  selector:
    app: guestbook
    tier: frontend
  externalIPs:
    - 192.168.0.38
# microk8s.kubectl apply -f frontend-service.yaml
# sudo microk8s.kubectl get services

