apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
        - name: slave
          image: gcr.io/google_samples/gb-redisslave:v1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
          env:
            # path to find master . isso é da aplicacao
            - name: GET_HOSTS_FROM
              #value: dns
# microk8s.kubectl apply -f redis-slave-deployment.yaml
# microk8s.kubectl get deployments
# microk8s.kubectl get pods
# microk8s.kubectl delete deployments/redis-slave
