apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# microk8s.kubectl apply -f claim.yaml
# microk8s.kubectl get persistentvolumeclaim or pvc
# microk8s.kubectl delete pvc/task-claim
